### PR TITLE
Silence Errors On Agent Version Check Connectivity Issues

### LINKED ISSUE #96: Should agent version startup check warn on GET failure?
### Current Behavior

If `github.com` is blocked in the firewall (a local artifactory repository is used instead), the `GET` operation will fail. Is there a good reason the current behavior is to `return err` rather than `return nil`?
https://github.com/newrelic/newrelic-lambda-extension/blob/8aba5246fa941f721a53f7ce5cda70f007ed5fa6/checks/runtime_check.go#L46-L50

The result is the following log line appears every time startup checks run:

```
[NR_EXT] There was an issue querying for the latest agent version: Get "https://github.com/newrelic/newrelic-python-agent/releases/latest": read tcp 169.254.76.1:58296->140.82.114.3:443: read: connection reset by peer
```

### Expected Behavior

No error log lines would appear on `GET` failure in the following scenarios:

1. Optional configuration to bypass the latest-version check.
2. Optional configuration to check a different URL (like a local artifactory site) instead of GitHub
3. Ignore `GET` failure with `return nil`.

### PR DESCRIPTION
**Pull request by kolanos**
Closes #96

This will still log the error if in debug mode.

### CODE REVIEW

**Review by mrickard — APPROVED** [review]

File: examples/sam/java/deploy.sh [hunk 1]
```diff
@@ -9,11 +9,11 @@ sam build --use-container
...
+#aws s3 mb --region ${region} s3://${bucket}
 
-sam package --region ${region} --s3-bucket=${bucket} --output-template-file packaged.yaml
-aws cloudformation deploy --region ${region} \
+sam package --region ${region} --s3-bucket ${bucket} --output-template-file packaged.yaml
+sam deploy --region ${region} \
   --template-file packaged.yaml \
-  --stack-name NewrelicExampleJava \
+  --stack-name NewrelicExampleJava2 \
   --capabilities CAPABILITY_IAM \
```
Comment (MattWhelan) [inline examples/sam/java/deploy.sh:18]: Did you mean to commit these?

**Review by MattWhelan — CHANGES_REQUESTED** [review]

File: examples/sam/java/deploy.sh (hunk 1 above)
Comment (kolanos) [reply examples/sam/java/deploy.sh:18]: @MattWhelan No, I thought I had reset those. Will revise it. Was only supposed to update to latest version.
